import Link from 'next/link';

export const metadata = {
  title: 'Terms of Service — BoDiGi 2.0',
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-slate-950 text-slate-300">
      <div className="max-w-3xl mx-auto px-6 py-16">
        <h1 className="text-3xl font-bold text-white mb-8">Terms of Service</h1>
        <div className="prose prose-invert prose-slate max-w-none space-y-6 text-sm leading-relaxed">
          <p className="text-slate-400">Last updated: September 5, 2026</p>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">1. Acceptance of Terms</h2>
            <p>By creating an account or using BoDiGi 2.0 (&ldquo;the Service&rdquo;), you agree to be bound by these Terms of Service. If you do not agree, do not use the Service.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">2. Description of Service</h2>
            <p>BoDiGi 2.0 is an AI-powered platform that generates application code from user-provided ideas. The Service uses AI agent teams to produce frontend, backend, database, testing, deployment, and documentation artifacts.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">3. User Accounts</h2>
            <p>You are responsible for maintaining the security of your account and password. You must provide a valid email address. You are fully responsible for all activity that occurs under your account.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">4. User Content</h2>
            <p>You retain ownership of any ideas, prompts, or content you submit to the Service. By submitting content, you grant BoDiGi 2.0 a license to process it through AI agents for the purpose of generating application code for you.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">5. Generated Content</h2>
            <p>Code and artifacts generated by BoDiGi 2.0 are provided for your use. You are responsible for reviewing, testing, and deploying generated code. BoDiGi 2.0 does not guarantee that generated code will be free of errors, security vulnerabilities, or other defects.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">6. Acceptable Use</h2>
            <p>You agree not to use the Service to: (a) generate malicious, illegal, or harmful software; (b) infringe on intellectual property rights; (c) spam or abuse the platform; (d) attempt to disrupt or compromise the Service.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">7. AI Disclaimer</h2>
            <p>BoDiGi 2.0 uses artificial intelligence to generate code. AI-generated content may contain errors, biases, or unexpected behavior. You are responsible for verifying the safety, legality, and functionality of all generated output.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">8. Limitation of Liability</h2>
            <p>BoDiGi 2.0 is provided &ldquo;as is&rdquo; without warranties of any kind. We are not liable for any damages arising from the use of generated code, including data loss, security issues, or business losses.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">9. Changes to Terms</h2>
            <p>We may update these Terms from time to time. Continued use of the Service after changes constitutes acceptance of the new Terms.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">10. Contact</h2>
            <p>For questions about these Terms, contact us through the BoDiGi 2.0 platform.</p>
          </section>
        </div>

        <div className="mt-12 pt-8 border-t border-slate-800">
          <Link href="/signup" className="text-purple-400 hover:text-purple-300 transition text-sm">
            ← Back to sign up
          </Link>
        </div>
      </div>
    </div>
  );
}
